### ISSUE TITLE
Azure documentation gone?

### ISSUE THREAD

**Issue by gscott** [mesosphere/open-docs#67]
Was formerly here: https://docs.mesosphere.com/install/azurecluster/ but now that's a redirect back to the /product page.

That old document at the link above described the use of the Azure Resource Manager template that still lives here: https://downloads.mesosphere.com/dcos/EarlyAccess/azuredeploy.json

Assumption is that Azure content should go in https://github.com/mesosphere/open-docs/tree/master/getting-started/cloud

**Comment by ssk2** [comment]
Thanks for the feedback @gscott, really appreciate the extra eyes! 

We're actually in the process of finalising our Azure templates - we were blocked on a few issues there. Since those templates will be deploying DCOS, that will live on docs.mesosphere.com when it's ready. I think the old template is still lying around and is linked to from http://open.mesosphere.com/reference/azure/. I'll make sure we update/remove that page as necessary.
